image: node:10.15.3
pipelines:
  branches:
    develop:
      - step:
          size: 2x
          name: Build app
          script: # The script below will build the application.
          - npm install
          - npm install -g @angular/cli
          - ng build --prod --progress=false
          artifacts:
          - dist/**
      - step:
          name: Deploy app
          script: # The script below will deploy the application to the webserver.
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: 'egovernance-test.portal'
                LOCAL_PATH: 'dist/EGovernanceWeb'
                ACL: 'public-read'
                DELETE_FLAG: 'true'
                EXTRA_ARGS: '--quiet'
    master:
      - step:
          size: 2x
          name: Build app
          script: # The script below will build the application.
          - npm install
          - npm install -g @angular/cli
          - ng build --prod --progress=false
          artifacts:
          - dist/**
      - step:
          name: Deploy app
          script: # The script below will deploy the application to the webserver.
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: 'foa-staging'
                LOCAL_PATH: 'dist/EGovernanceWeb'
                ACL: 'public-read'
                DELETE_FLAG: 'true'
                EXTRA_ARGS: '--quiet'